[build]

[deploy]
startCommand = "node init-data.js && node server.js"

[service]
env = { 
	NODE_ENV = "production",
	PORT = "3000",
	PUBLIC_BASE_URL = "https://talentsync.shop",
	SITE_URL = "https://talentsync.shop",
	SESSION_SECRET = "set-in-railway",
	JWT_SECRET = "set-in-railway",
	EMAIL_USER = "set-in-railway",
	EMAIL_PASS = "set-in-railway",
	EMAIL_FROM = "talentsync@talentsync.shop",
	SMTP_HOST = "",
	SMTP_PORT = "587",
	SMTP_SECURE = "false",
	RESET_DEBUG = "false",
	AUTH_RATE_WINDOW_MS = "900000",
	AUTH_RATE_MAX = "20",
	ADMIN_NOTIFY_EMAIL = "set-in-railway",
	STRIPE_SECRET_KEY = "set-in-railway",
	STRIPE_PRICE_BASIC = "set-in-railway",
	STRIPE_PRICE_PRO = "set-in-railway",
	STRIPE_WEBHOOK_SECRET = "set-in-railway"
}